# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: |
    pip install selenium
    # 기타 필요한 패키지 설치

    # Chrome 브라우저의 헤드리스 모드 설정
    from selenium import webdriver
    from selenium.webdriver.chrome.options import Options

    options = Options()
    options.add_argument('--headless')
    options.add_argument('--disable-gpu')
    driver = webdriver.Chrome(options=options)

    # Azure DevOps Repos에서 셀레니움 코드 가져오기
    with open('https://Security365@dev.azure.com/Security365/Test%20Project/_git/Selenium_Test/Selenium_Test_Run.py', 'r') as file:
        code = file.read()

    # 셀레니움 코드 실행
    exec(code)
    # 셀레니움 작업이 완료되면 브라우저 종료
    driver.quit()
  displayName: 'Run Selenium Headless'
