# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10.4'
    addToPath: true

# - script: |
#   sudo apt-get update
#    sudo apt-get install -y chromium-chromedriver
#   sudo chmod +x /usr/lib/chromium-browser/chromedriver
# displayName: 'Install Chromium WebDriver'

- script: |
    pip install selenium==4.1.4
    pip install chromedriver-autoinstaller
    python Selenium_Test_Run.py
  displayName: 'Run Selenium Headless'

